### ISSUE TITLE
android HAL for RISCV

### ISSUE THREAD

**Issue by pankajjoshi347** [aosp-riscv/working-group#20]
Hi,
i am trying to understand can i use the same HAL sources provided by AOSP for RISC-V or porting is required for that as well as ? If yes, what and all elements needs to be changed ? Can someone guide me with this ??

Thanks

**Comment by unicornx** [comment]
hi,
This repo/project is from [PLCT-lab](https://github.com/isrc-cas/), we had stopped this work due to another AOSP porting on RISC-V project from T-Head make bigger progress, you can get the latest info about that from <https://github.com/T-head-Semi/aosp-riscv>.

Our work here on AOSP for RISC-V finished the porting of bionic (with static link and dynamic link) and successfully boot linux and rootfs with simple native application on QEMU emulator, we have not completed support of java part yet.  If you want to reuse our code, you may have to complete other parts, and if you are testing on a real hardware, you also need to port the hardware part such as drivers and etc.

**Comment by unicornx** [comment]
closed due to it is a long history issue
