### ISSUE TITLE
porting create_minidebuginfo

### ISSUE THREAD

**Issue by unicornx** [aosp-riscv/working-group#24]
create_minidebuginfo is a prebuilt tools under `prebuilts/build-tools/linux-x86/bin/create_minidebuginfo`, it has not supported riscv. During building, for example "mmm bionic". `build/soong/scripts/strip.sh` will call this executable to do strip. But now it can not work for riscv64. Now to make building pass w/o blocking, we just comment and ignore the strip work temporally and `echo "TBD: CREATE_MINIDEBUGINFO has NOT been supported!!!!!!!"`.

Need to make it support riscv.

FYI, the source code of this tool is under `art/tools/create_minidebuginfo/`, need to investigate if we can implement it first before we start ART porting.

create this issue here in working-group, when analysis work done, we will create proper issue in correct repo (art?) to track the actual dev work.

Please provide a summary report when you finish this.

**Comment by BroSheng** [comment]
I'm happy to do this part.

**Comment by BroSheng** [comment]
Update:

I will start to work on it tomorrow. Sorry for the late.

**Comment by BroSheng** [comment]
Update:

The create_minidebuginfo has a dependency that is inside the AOSP prebuilt. Rebuilding of the prebuilds is needed. I'm currently figuring out how to rebuild it, which may involve Android.mk files.

**Comment by BroSheng** [comment]
Update:

I've already updated the dependencies that `create_minidebuginfo` needed. Now it seems like working correctly.

First, delete the annotation in `/aosp/build/soong/scripts/strip.sh`, so that the script will use the create_minidebuginfo. You could simply apply the [Pull Request: Enable create_minidebuginfo](https://github.com/aosp-riscv/platform_build_soong/pull/2) of [aosp-riscv/platform_build_soong](https://github.com/aosp-riscv/platform_build_soong/).

The instruction for applying the new `create_minidebuginfo` is already in [Pull Request: Updated dependencies needed by create_minidebuginfo](https://github.com/aosp-riscv/platform_art/pull/1) of [aosp-riscv/platform_art](https://github.com/aosp-riscv/platform_art).

For convenience, I wonder if you could create a new repository for `aosp/prebuilts`, so that we could update the prebuilt `create_minidebuginfo`, then others will be able to use it directly later.

**Comment by unicornx** [comment]
just for memo, later we can sum up the PRs here if your changes touch more than 1 repo
- https://github.com/aosp-riscv/platform_build_soong/pull/2
- https://github.com/aosp-riscv/platform_art/pull/1

**Comment by unicornx** [comment]
Please investigate why Google use create_minidebuginfo create a special section and insert into the final stripped executable. A simple research report is required to fill this issue. We need this to check if your change does work correctly and test it out.

**Comment by BroSheng** [comment]
Update: Still working on the analysis of create_minidebuginfo, I have got some progress already, you may expect it to be finished by the end of January.

**Comment by BroSheng** [comment]
Update: the [Analysis of create_minidebuginfo](https://zhuanlan.zhihu.com/p/463363360) has been posted. Follow the link to read the report. Happy new year by the way.

**Comment by unicornx** [comment]
> Update: the [Analysis of create_minidebuginfo](https://zhuanlan.zhihu.com/p/463363360) has been posted. Follow the link to read the report. Happy new year by the way.

hi, Sheng, I will try to check it out after my spring festival vacation on Feb/14.

**Comment by unicornx** [comment]
> > Update: the [Analysis of create_minidebuginfo](https://zhuanlan.zhihu.com/p/463363360) has been posted. Follow the link to read the report. Happy new year by the way.
> 
> hi, Sheng, I will try to check it out after my spring festival vacation on Feb/14.

Nice writing! Additionally, if you can add some background knowledge of this tool would be better. FYI, it is a feature called "MiniDebugInfo", you can check  gdb manual <https://sourceware.org/gdb/onlinedocs/gdb/MiniDebugInfo.html> for more details.

I also have reviewed your code changes, please check https://github.com/aosp-riscv/platform_art/pull/1#issuecomment-1038613388 for more details.

**Comment by BroSheng** [comment]
Update: Need more time to do the git-rebase. Due to my midterms, expect more changes starting from next week. I'll finish my midterms by the end of this week. I wonder that do you mean to sync the aosp-riscv/platform_art with RVI upstream by myself, or only do the rebase of my work and combine into my PR for aosp-riscv/platform_art?

**Comment by unicornx** [comment]
> Update: Need more time to do the git-rebase. Due to my midterms, expect more changes starting from next week. I'll finish my midterms by the end of this week. I wonder that do you mean to sync the aosp-riscv/platform_art with RVI upstream by myself, or only do the rebase of my work and combine into my PR for aosp-riscv/platform_art?

Only sync the files you touched, not the whole platform_art repo.
