### ISSUE TITLE
bionic test: stack_unwinding

### ISSUE THREAD

**Issue by unicornx** [aosp-riscv/working-group#40]
Please refer to https://gitee.com/aosp-riscv/working-group/issues/I4MEG2 for details.

**Comment by liushuyu** [comment]
This is taking longer than expected.

The difficulty is currently on the debugging: debugging through qemu's gdb stub is a bit problematic since stack frame information is not available. This would slow down the debugging process but it is still possible to continue the work regardless albeit slower.

**Comment by unicornx** [comment]
will close this issue, due to no progress for a long time, and we have another thread at <https://gitee.com/aosp-riscv/working-group/issues/I5D6NY>.
