### ISSUE TITLE
Is there room for a beginner? 

### ISSUE THREAD

**Issue by teezzan** [aosp-riscv/working-group#6]
Hello everyone,
As a newbie to Android development, is there a way to contribute to this port? While my Java skills isn't world class, I believe I might have what it takes to learn how to be useful across board.
Also, is there any kind of communication channel or group which I can join to facilitate my question asking and integration into the community? 

Thanks.

**Comment by unicornx** [comment]
Hello, Teezzan,
This project is target to porting android on risc-v arch, and due to android(AOSP) contains tons of staffs, it is a huge task and everyone can choose part of them that he is interested in. What's your interest？

Regarding your question about comm channel or group, 
For Android porting, <https://groups.google.com/g/android-porting> may be related, but according to my observation, few people concerns risc-v.
For RISC-V related, you can visit <https://groups.google.com/a/groups.riscv.org/g/sw-dev>.

And you can also join us on this porting work, any contribution is welcomed.

**Comment by unicornx** [comment]
@teezzan , any input from you? Or can I close this issue?

**Comment by teezzan** [comment]
Thanks. I checked the link and found more info. Thanks
